dataset:
  observation_fieldnames:
     - index
     - sentence
     - lemma_sentence
     - upos_sentence
     - xpos_sentence
     - morph
     - head_indices
     - governance_relations
     - secondary_relations
     - extra_info
     - embeddings

  embeddings:
    type: subword #{token,subword}

  batch_size: 32
model:
  hidden_dim: 768 # ELMo hidden dim
  #embedding_dim: 768 # ELMo word embedding dim
  model_type: BERT-disk-cum # BERT-disk, ELMo-disk,
  use_disk: True
  model_layer: 11 # BERT-base: {1,...,12}; ELMo: {1,2,3}
probe:
  task_signature: word_pair # word, word_pair
  task_name: parse-distance
  maximum_rank: 768
  psd_parameters: True
  cumulative: True
  diagonal: False
  params_path: predictor.params
probe_training:
  epochs: 40
  loss: L1
reporting:
  observation_paths:
    train_path: train.observations
    dev_path: dev.observations
    test_path: test.observations
  prediction_paths:
    train_path: train.predictions
    dev_path: dev.predictions
    test_path: test.predictions
  reporting_methods:
    - write_predictions
    - state
